### ISSUE TITLE
Using httpclient.get() to load translated file and using NgTransService in Interceptor, it will not load the default lang translated file

### ISSUE THREAD

**Issue by bigBear713** [bigBear713/ng-translation#2]
**Version**: 12.0.0

**Description**: Using httpclient.get() to load translated file and using NgTransService in Interceptor, it will not do the load default lang translated file. And if loading the file by manual in trans loader factory, there is a Circular dependency error.

**Code**
```ts
  // AppModule
  providers: [
    [
      {
        provide: HTTP_INTERCEPTORS, useClass: Interceptor, multi: true,
      },
    ],
    {
      provide: NG_TRANS_LOADER,
      useFactory: (http: HttpClient) => {
        // if loading the file by manual, there is a Circular dependency error.
        http.get('./assets/localization/zh-CN/translations.json').subscribe(data => console.log(data));
        return {
          [NgTransLangEnum.ZH_CN]: () => http.get('./assets/localization/zh-CN/translations.json'),
          [NgTransLangEnum.EN]: () => http.get('./assets/localization/en/translations.json'),
        }
      },
      deps: [HttpClient]
    },
  ],

@Injectable()
export class Interceptor implements HttpInterceptor {

    constructor(
        private transService: NgTransService,
    ) { }

    intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
        let headers = req.headers;
        headers = this.setLanguage(headers);

        const newReq = req.clone({ headers, });
        return next.handle(newReq);
    }

    private setLanguage(headers: HttpHeaders): HttpHeaders {
        const currLang = this.transService.lang;
        return headers.append('Language', langMapping[currLang]);
    }
}
```

**Error**
```
ERROR Error: NG0200: Circular dependency in DI detected for NgTransService. Find more at https://angular.io/errors/NG0200
    at throwCyclicDependencyError (core.js:216:1)
    at R3Injector.hydrate (core.js:11441:1)
    at R3Injector.get (core.js:11264:1)
    at injectInjectorOnly (core.js:4758:1)
    at Module.ɵɵinject (core.js:4762:1)
    at Object.Interceptor_Factory [as factory] (interceptor.ts:34:36)
    at R3Injector.hydrate (core.js:11445:1)
    at R3Injector.get (core.js:11264:1)
    at injectInjectorOnly (core.js:4758:1)
    at ɵɵinject (core.js:4762:1)
```

**Comment by bigBear713** [comment]
In the case, using httpClient to load translated file, so the request will go through the interceptor. And using NgTransService in Interceptor, so it fails, will not do the request.

At that time, we can create a new httpClient instance so that the new instance will ignore the `HTTP_INTERCEPTORS`, the problem will not exist. 

Creating a new HttpClient instance, we need a `HttpBackend` value, like this:
```ts
  // AppModule
  providers: [
    [
      {
        provide: HTTP_INTERCEPTORS, useClass: Interceptor, multi: true,
      },
    ],
    {
      provide: NG_TRANS_LOADER,
      useFactory: (httpBackend: HttpBackend) => {
        const http = new HttpClient(httpBackend);
        return {
          [NgTransLangEnum.ZH_CN]: () => http.get('./assets/localization/zh-CN/translations.json'),
          [NgTransLangEnum.EN]: () => http.get('./assets/localization/en/translations.json'),
        }
      },
      deps: [HttpBackend]
    },
  ],
```
It work fine now!
